-- -----------------------------------------------------
-- Table `RASPBERRY_FEATURE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RASPBERRY_FEATURE` (
  `FEATURE_ID` INT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(100) NULL,
  `DESCRIPTION` VARCHAR(200) NULL,
  PRIMARY KEY (`FEATURE_ID`) )
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RASPBERRY_DEVICE`
-- -----------------------------------------------------


  CREATE  TABLE IF NOT EXISTS `RASPBERRY_DEVICE` (
  `RASPBERRY_DEVICE_ID` VARCHAR(45) NOT NULL,
  `USERNAME` VARCHAR(100) NULL DEFAULT NULL,
  `PASSWORD` VARCHAR(100) NULL DEFAULT NULL,
  `SERIAL` VARCHAR(45) NULL DEFAULT NULL,
  `VERSION` VARCHAR(45) NULL DEFAULT NULL,
  `MAC_ADDRESS` VARCHAR(45) NULL DEFAULT NULL,
  `DEVICE_NAME` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`RASPBERRY_DEVICE_ID`) )
  ENGINE = InnoDB;
